### ISSUE TITLE
Add verification for the ICM-42607 IMU variant

### ISSUE THREAD

**Issue by pedrominatel** [jessebraham/icm42670#2]
The mass production variant of the ICM-42670 is the ICM-42607.

This variant is the ``0x60`` and should be tested as well. The final version of the Rust Board will be populated with the ICM-42607.

https://github.com/jessebraham/icm42670/blob/95ea1dcf2ecdafc0ad52b780e43dff971a705e72/src/lib.rs#L64

**Comment by jessebraham** [comment]
Thanks for bringing this to my attention! I have added support for this second device in [this commit](https://github.com/jessebraham/icm42670/commit/eb0483bbb0ec485b35c8d38c1f36a02bcc899e0a).
